### ISSUE TITLE
RuntimeError: Unable to open checkpoints/shape_predictor_68_face_landmarks.dat

### ISSUE THREAD

**Issue by xueli2015** [Winfredy/SadTalker#112] opened 2023-04-11 13:52 UTC
I have to download this file mannually. it does work now.

checkpoints/shape_predictor_68_face_landmarks.dat
Traceback (most recent call last):
  File "/workspace/anaconda3/envs/sadtalker/lib/python3.8/site-packages/gradio/routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "/workspace/anaconda3/envs/sadtalker/lib/python3.8/site-packages/gradio/blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "/workspace/anaconda3/envs/sadtalker/lib/python3.8/site-packages/gradio/blocks.py", line 916, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/workspace/anaconda3/envs/sadtalker/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/workspace/anaconda3/envs/sadtalker/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/workspace/anaconda3/envs/sadtalker/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/workspace/SadTalker/src/gradio_demo.py", line 64, in test
    self.preprocess_model = CropAndExtract(self.path_of_lm_croper, self.path_of_net_recon_model, self.dir_of_BFM_fitting, self.device)
  File "/workspace/SadTalker/src/utils/preprocess.py", line 45, in __init__
    self.croper = Croper(path_of_lm_croper)
  File "/workspace/SadTalker/src/utils/croper.py", line 38, in __init__
    self.predictor = dlib.shape_predictor(path_of_lm)
RuntimeError: Unable to open checkpoints/shape_predictor_68_face_landmarks.dat

**Comment by Mu2u** [comment] 2023-04-11 15:07
I also have this issue ,I downloaded it from google drive and replaced the file but still no good.  Running on Linux Debian

**Comment by vinthony** [comment] 2023-04-11 15:15
> where did you download it from? Google drive?

please download it from github release. google driver lack of mapping108.pth

**Comment by Javeray** [comment] 2023-04-14 03:27
i got the same 'RuntimeError',

firstly, i confirmed that i have alreadly executed the 'scripts/download_models.sh'.
and then i confirmed the urls and md5 values of those model files which mentioned above.
at the end i tried creating a symbol link under the project root directory, and it works. nice~

ps: creating a symbol link under the project root directory like this:
ln -s scripts/checkpoints ./checkpoints

i hope it helps.

**Comment by vinthony** [comment] 2023-04-14 03:30
> 

It seems you have `cd scripts` and then run the bash command.

you need to do it in the root of the project by `bash scripts/download_models.sh`

**Comment by Javeray** [comment] 2023-04-14 04:17
@vinthony oh, you are right, that is the cause.

**Comment by vinthony** [comment] 2023-04-14 04:40
I will close this issues if anyone have new updates please feel free to reopen it.

**Closed by vinthony** 2023-04-14 04:40 UTC

**Comment by LIUXINGSD** [comment] 2023-04-26 15:56
还是解决不了

**Comment by vinthony** [comment] 2023-04-26 16:29
checkpoints目录在你的SadTalker的根目录下面就行，类似我这里：
![image](https://user-images.githubusercontent.com/4397546/234641575-ad1068a4-6ada-4d11-8761-4ce55fdf1a76.png)
